### PR TITLE
Add: PHP 8.0

### LINKED ISSUE #190: PHP 8 Support
**Is your enhancement related to a problem? Please describe.**
* No

**Describe the solution you'd like**
* Allow PHP 8 Support using the available 10up/wp-php-fpm 8.0 image.

**Designs**
* None currently happy to open a quick PR though.

**Describe alternatives you've considered**
* Running my own docker setup, though I like the automation of 10up docker better for personal projects.

**Additional context**
I've been working with PHP 8 a lot lately and it's really grown on me. However, I noticed 10up Docker doesn't currently have PHP 8 support. So I started looking through the source. I figured, hey, why not see if I can get it running, but I ran into a bit of an issue.

I see that there are [constants available](https://github.com/10up/wp-local-docker-v2/blob/d864ebb3f8eba23662b05a55d482a2f2be3cb646/src/commands/create/inquirer.js#L4) in the script which reference PHP versions. Thinking that'd be an easy change I wanted to dig a bit deeper. I unearthed where the [docker-compose is created](https://github.com/10up/wp-local-docker-v2/blob/e2f14c5d8be20cdde92646dbd75fa0b567db7df3/src/commands/create/make-docker-compose.js#L48) and found that the images in use are [10up images only](https://github.com/10up/wp-local-docker-v2/blob/e2f14c5d8be20cdde92646dbd75fa0b567db7df3/src/docker-images.js#L9) ( for php-fpm ). This should be a pretty quick edit, but I'm unsure how stable the [8.0 tagged image](https://hub.docker.com/r/10up/wp-php-fpm/tags?page=1&ordering=last_updated&name=8.0) is, wondering if @dustinrue can weigh in?

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR adds PHP 8.0 support using `10up/wp-php-fpm-dev:8.0` image.

### Verification Process
1. Uninstall `wp-local-docker` and install this branch using `npm install https://github.com/dinhtungdu/wp-local-docker-v2\#cf27c20b -g`.
2. Run `10updocker create`
3. See PHP 8.0 option.

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues
Fixes #190

### Changelog Entry

Added support for PHP 8.0.

### CODE REVIEW

**Comment by eugene-manuilov** [comment]
This is very nice, @dinhtungdu! Could you please update the changelog file too?

**Comment by tylercherpak** [comment]
@dinhtungdu @eugene-manuilov Is there anything we need to do as far as upgrade path goes? I assume not but wanted to check since the instructions were to uninstall before installing this version.

**Comment by dinhtungdu** [comment]
@eugene-manuilov I updated the changelog file.

@tylercherpak I think just updating the command is fine.

**Review by eugene-manuilov — APPROVED** [review]
Awesome! Thanks, @dinhtungdu.

**Comment by jeffpaul** [comment]
@eugene-manuilov should we rebase this to `release/2.8.2` and merge there?

**Review by eugene-manuilov — APPROVED** [review]

**Pull request merged**
